version: '3.4'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
 

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.5.1
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: 127.0.0.1
      SERVER_HOST: 0.0.0.0
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - esnet

  fluentd:
    container_name: fluentd
    image: "custom/fluentd"
    depends_on:
      - elasticsearch
    networks:
      - esnet
      - eventing
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24226:24226"
      - "24226:24226/udp"    

volumes:
  esdata1:
    driver: local


networks:
  esnet:
    external: true
  eventing:
    external: true

